### ISSUE TITLE
genomeToProtein's output contains metadata with two identical tx_id columns

### ISSUE THREAD

**Issue by kotliary** [jotsetung/ensembldb#136]
I believe this is due to using `cbind`. 

```
mcols(prts) <- cbind(mcols(prts)[, c("tx_id", "cds_ok")], mcols(txs))
```
Probably "tx_id" can be removed here.

**Comment by jorainer** [comment]
Good catch! I've fixed it in the release branch (Bioconductor 3.15) and the developmental version. Changes should get propagated in the next couple of days and the package can then be updated with `BiocManager::install()`.

Closing  the issue now. Feel free to re-open if needed.
