### ISSUE TITLE
`ensembldb` failing on Bioc devel (3.17)

### ISSUE THREAD

**Issue by bschilder** [jotsetung/ensembldb#143]
Just a heads up, `ensembldb` is currently failing on Bioc devel (3.17):
https://bioconductor.org/packages/devel/bioc/html/ensembldb.html

The crux of the error is:
```R
Error in setMethod("disjointExons", "EnsDb", function(x, aggregateGenes = FALSE,  : 
  no existing definition for function ‘disjointExons’
```
http://bioconductor.org/checkResults/devel/bioc-LATEST/ensembldb/nebbiolo1-install.html

**Comment by bschilder** [comment]
Ah sorry, just saw this: #142 
Thanks for working on this!

**Comment by bschilder** [comment]
Seems to be working again, both both release and devel. Thanks!
https://bioconductor.org/packages/devel/bioc/html/ensembldb.html

**Comment by jorainer** [comment]
Anyway, thanks for reporting! - and sorry for the late reply :)
