### ISSUE TITLE
EnsDb for Ovis aries

### ISSUE THREAD

**Issue by prispi86** [jotsetung/ensembldb#145]
Hello,
I have tried to generate an specific EnsDb for sheep (Ovis aries), but I could only generate the package for a specific sheep breed (Texel) with this annotation: https://www.ensembl.org/Ovis_aries/Info/Annotation

I would need to create it for this annotation: https://www.ensembl.org/Ovis_aries_rambouillet/Info/Annotation

But I could not find the record.

Could you help me, please?

Thank you so much,

Priscila

**Comment by jorainer** [comment]
Thanks for the info! I didn't realize that databases for specific breeds or similar were not generated. I am anyway currently in the process of creating the data for Ensembl 109 and will include them.

Would you need an `EnsDb` for a specific Ensembl release? I could provide that separately

**Comment by prispi86** [comment]
Thank you so much! The most recent available release would be great, as long as it is for Ovis aries rambouillet:
https://www.ensembl.org/Ovis_aries_rambouillet/Info/Annotation
Thank you and have a nice day!

**Comment by jorainer** [comment]
You can get the `EnsDb` sqlite database from [here](https://www.dropbox.com/sh/wglt28zlfzhjubs/AADzGqJ0zydKRmdqbOsH_Ru5a?dl=0) . just download it and load it with `edb <- EnsDb("EnsDb.Oaries.Oar_rambouillet_v1.0.v109.sqlite")`. This will also become available through `AnnotationHub` later.

**Comment by prispi86** [comment]
Thank you so much for your help!

**Comment by jorainer** [comment]
I'm closing the issue now - feel free to re-open if needed.
