### ISSUE TITLE
Support for parallel query for coordinates mappings

### ISSUE THREAD

**Issue by Tim-Yu** [jotsetung/ensembldb#149]
Hi,

I am recently doing some fun projects using HPC and noticed that the coordinates mapping tools do not support parallel queries due to the limitation of SQLite. Therefore I made some [modifications](https://github.com/Tim-Yu/ensembldb/commit/646abbd44537a13aa21d0c73cc905cc026fa7eb5) to the transcriptToGenome function, enabling users to use pre loaded exons for running parallel jobs.

I thought it might be helpful for the others interested in parallel queries. If you also found this interesting, I may update other functions and create a PR?

Best wishes,

Tim

**Comment by jorainer** [comment]
Hey Tim,

that looks great, yes, please, go ahead and make a PR. 

Maybe some questions beforehand: is there a particular reason to use a `CompressedGRangesList` instead of a *standard* `GRAngesList`? Also, for the PR, please also add unit tests for your new code.

Thanks!
