### ISSUE TITLE
Need help building EnsDb.Rnorvegicus.v112

### ISSUE THREAD

**Issue by NewtontheNeuron** [jotsetung/ensembldb#160]
Hello,

I have been trying to follow the vignette in order to build EnsDb.Rnorvegicus.v112 for a project. All of the code from the vignette on bioconductor's website works perfectly. However, due to limitations on my HPC, I am unable to download it via a scheduler. As a result, my terminal session usually times out before the download can finish.

The only download that was continuous using `fetchTablesFromEnsembl()` was run in an Rscript like this: `Rscript <yourscript.R> &`. Then I used `disown` to detach it from my terminal session. It ran for about 24hrs. However, when I run `DBFile <- makeEnsemblSQLiteFromTables()`, I get the following very common error.
```bash
Error in makeEnsemblSQLiteFromTables() :
  Something went wrong! I'm missing some of the txt files the perl script should have generated.
```
**Here are the files that I downloaded.**
![image](https://github.com/user-attachments/assets/6514c95e-0584-4b84-8523-042bb2342767)

**ensembldb/R/functions-create-EnsDb.R**
https://github.com/jorainer/ensembldb/blob/230d2b698673dc646e88f20ce8cf1f6bfbde0ecd/R/functions-create-EnsDb.R#L71-L79

I've determined from following the code in the source of `makeEnsemblSQLiteFromTables()` function that I have every file except the `"ens_metadata.txt"` file. I am not sure if that was an error with download (because it could have been terminated by the HPC maintainers without me knowing) or just that some species/releases do not have the metadata file. _Is there a way to specifically download the metadata file?_

Your guidance will be much appreciated.

**Comment by jorainer** [comment]
Dear @NewtontheNeuron , note that there are pre-built `EnsDb` databases for all Ensembl versions and all species available through Bioconductor's `AnnotationHub`. I would suggest therefore to use one of these instead of building one yourself (from own experience I am pretty aware that configuring the Perl setup to create them is quite tricky).

To get the version you need (Rnorvegicus for Ensembl 112):

```r
> library(AnnotationHub)
> ah <- AnnotationHub()
> query(ah, "EnsDb.Rnorvegicus.v112")
AnnotationHub with 1 record
# snapshotDate(): 2024-04-30
# names(): AH116989
# $dataprovider: Ensembl
# $species: Rattus norvegicus
# $rdataclass: EnsDb
# $rdatadateadded: 2024-04-30
# $title: Ensembl 112 EnsDb for Rattus norvegicus
# $description: Gene and protein annotations for Rattus norvegicus based on ...
# $taxonomyid: 10116
# $genome: mRatBN7.2
# $sourcetype: ensembl
# $sourceurl: http://www.ensembl.org
# $sourcesize: NA
# $tags: c("112", "Annotation", "AnnotationHubSoftware", "Coverage",
#   "DataImport", "EnsDb", "Ensembl", "Gene", "Protein", "Sequencing",
#   "Transcript") 
# retrieve record with 'object[["AH116989"]]' 
> edb <- ah[["AH116989"]]
```

Note: this requires R version 4.4 and Bioconductor 3.19.

**Comment by NewtontheNeuron** [comment]
Thank you so much! This works perfectly. I for some reason thought that only the builds listed as Bioconductor packages were prebuilt. That was an error on my part.

Thanks :)
